# config.yaml

source_type: file
source: data/sample.xml

prefixes:
  dcterms: "http://purl.org/dc/terms/"
  foaf: "http://xmlns.com/foaf/0.1/"
  schema: "http://schema.org/"
  fabio: "http://purl.org/spar/fabio/"

uri_patterns:
  subject_uri: "https://example.org/record/{ID}"
  object_uri: "{subject_uri}/{field}/{index}"

fields:
  ID: 
    tag: "001"
    code: ""
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:identifier"
          object: "{value}"
  AUTHOR:
    tag: "100"
    code: "a"
    cleaning:
      - func: pattern_replace
        patterns:
          - '[.,!\[\]?:;]+$'
          - '^\s+|\s+$'
        replacement: ""
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:creator"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "rdf:type"
          object: "foaf:Person"
        - subject: "{object_uri}"
          predicate: "foaf:name"
          object: {value}
  TITLE:
    tag: "245"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:title"
          object: "{value}"
  SUBTITLE:
    tag: "245"
    code: "b"
    cleaning:
      - func: pattern_replace
        patterns:
          - '\s{2,}'
        replacement: " "
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "fabio:hasSubtitle"
          object: "{value}"
  PUB_PLACE: 
    tag: "260"
    code: "a"
    cleaning:
      - func: pattern_replace
        patterns:
          - '^\s+|\s+$'
        replacement: ""
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "fabio:hasPlaceOfPublication"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "rdf:type"
          object: "schema:Place"
        - subject: "{object_uri}"
          predicate: "schema:name"
          object: "{value}"
  PUBLISHER: 
    tag: "260"
    code: "b"
    cleaning:
      - func: pattern_replace
        patterns:
          - '\[s\.n\.\]'
          - '\[s\.l\.\]'
          - 'n\.d\.'
          - 'nan'
          - '-'
          - 'none'
        replacement: "NaN"
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:publisher"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "rdf:type"
          object: "foaf:Agent"
        - subject: "{object_uri}"
          predicate: "foaf:name"
          object: "{value}"
  PUB_DATE: 
    tag: "260"
    code: "c"
    cleaning:
      - func: pattern_extract
        pattern: '(\d{4})'
        group: 1
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "fabio:hasPublicationYear"
          object: "{value}"
  NOTE: 
    tag: "500"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:description"
          object: "{value}"
  ALT_ID: 
    tag: "035"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:identifier"
          object: "{value}"