source_type: file
source: data/sample.xml

# Define the path where the raw files will be collected
raw_data_path: data/raw

# Define the path where the processed data will be collected
processed_data_path: data/processed

# Fields
fields:
  ID: 
    tag: "001"
    code: ""
  AUTHOR:
    tag: "100"
    code: "a"
  TITLE:
    tag: "245"
    code: "a"
  SUBTITLE:
    tag: "245"
    code: "b"
  PUB_PLACE: 
    tag: "260"
    code: "a"
  PUBLISHER: 
    tag: "260"
    code: "b"
  PUB_DATE: 
    tag: "260"
    code: "c"
  NOTE: 
    tag: "500"
    code: "a"
  ALT_ID: 
    tag: "035"
    code: "a"