# config.yaml

source_type: file
source: data/

outputs:
  - type: rdf
    format: ttl
  - type: table
    format: csv
    exclude_fields:
      - CLASS
  - type: table
    format: xlsx
    exclude_fields:
      - CLASS
  - type: table
    format: json
    exclude_fields:
      - CLASS
  - type: table
    format: sql
    exclude_fields:
      - CLASS

prefixes:
  dcterms: "http://purl.org/dc/terms/"
  fabio: "http://purl.org/spar/fabio/"
  foaf: "http://xmlns.com/foaf/0.1/"
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  schema: "http://schema.org/"
  xsd: "http://www.w3.org/2001/XMLSchema#"

uri_patterns:
  base_uri: "https://example.org"
  subject_uri: "{base_uri}/record/{ID}"
  object_uri: "{subject_uri}/{field}/{index}"


fields:
  CLASS:
    subject_class: "http://purl.org/spar/fabio/Work"
    mapping:
      type: direct
      template: []
  ID: 
    tag: "001"
    code: ""
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/dc/terms/identifier"
          object: "{value}"
          datatype: "http://www.w3.org/2000/01/rdf-schema#Literal"
  AUTHOR:
    tag: "100"
    code: "a"
    cleaning:
      - func: pattern_replace
        patterns:
          - '[.,!\[\]?:;]+$'
          - '^\s+|\s+$'
        replacement: ""
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/dc/terms/creator"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
          object: "http://xmlns.com/foaf/0.1/Person"
        - subject: "{object_uri}"
          predicate: "http://xmlns.com/foaf/0.1/name"
          object: "{value}"
          datatype: "http://www.w3.org/2000/01/rdf-schema#Literal"
      uri_strategy: "global"
      uri_pattern: "{base_uri}/person/{normalized_value}"
  TITLE:
    tag: "245"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/dc/terms/title"
          object: "{value}"
          datatype: "http://www.w3.org/2000/01/rdf-schema#Literal"
  SUBTITLE:
    tag: "245"
    code: "b"
    cleaning:
      - func: pattern_replace
        patterns:
          - '\s{2,}'
        replacement: " "
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/spar/fabio/hasSubtitle"
          object: "{value}"
          datatype: "http://www.w3.org/2000/01/rdf-schema#Literal"
  PUB_PLACE: 
    tag: "260"
    code: "a"
    cleaning:
      - func: pattern_replace
        patterns:
          - '^\s+|\s+$'
        replacement: ""
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/spar/fabio/hasPlaceOfPublication"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
          object: "http://schema.org/Place"
        - subject: "{object_uri}"
          predicate: "http://schema.org/name"
          object: "{value}"
          datatype: "http://www.w3.org/2000/01/rdf-schema#Literal"
      uri_strategy: "global"
      uri_pattern: "{base_uri}/place/{normalized_value}"
  PUBLISHER: 
    tag: "260"
    code: "b"
    cleaning:
      - func: pattern_replace
        patterns:
          - '\[s\.n\.\]'
          - '\[s\.l\.\]'
          - 'n\.d\.'
          - 'nan'
          - '-'
          - 'none'
        replacement: ""
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/dc/terms/publisher"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
          object: "http://xmlns.com/foaf/0.1/Agent"
        - subject: "{object_uri}"
          predicate: "http://xmlns.com/foaf/0.1/name"
          object: "{value}"
          datatype: "http://www.w3.org/2000/01/rdf-schema#Literal"
      uri_strategy: "global"
      uri_pattern: "{base_uri}/agent/{normalized_value}"
  PUB_DATE: 
    tag: "260"
    code: "c"
    cleaning:
      - func: pattern_extract
        pattern: '(\d{4})'
        group: 1
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/spar/fabio/hasPublicationYear"
          object: "{value}"
          datatype: "http://www.w3.org/2001/XMLSchema#gYear"
  NOTE: 
    tag: "500"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/dc/terms/description"
          object: "{value}"
          datatype: "http://www.w3.org/2000/01/rdf-schema#Literal"
  ALT_ID: 
    tag: "035"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "http://purl.org/dc/terms/identifier"
          object: "{value}"
          datatype: "http://www.w3.org/2000/01/rdf-schema#Literal"