source_type: file
source: data/sample.xml

# Define the path where the raw files will be collected
raw_data_path: data/raw

# Define the path where the processed data will be collected
processed_data_path: data/processed

# Fields
fields:
  ID: 
    tag: "001"
    code: ""
  AUTHOR:
    tag: "100"
    code: "a"
    cleaning:
      - func: pattern_replace
        patterns:
          - '[.,!\[\]?:;]+$'
          - '^\s+|\s+$'
        replacement: ""
  TITLE:
    tag: "245"
    code: "a"
  SUBTITLE:
    tag: "245"
    code: "b"
    cleaning:
      - func: pattern_replace
        patterns:
          - '\s{2,}'
        replacement: " "
  PUB_PLACE: 
    tag: "260"
    code: "a"
    cleaning:
      - func: pattern_replace
        patterns:
          - '^\s+|\s+$'
        replacement: ""
  PUBLISHER: 
    tag: "260"
    code: "b"
    cleaning:
      - func: pattern_replace
        patterns:
          - '\[s\.n\.\]'
          - '\[s\.l\.\]'
          - 'n\.d\.'
          - 'nan'
          - '-'
          - 'none'
        replacement: "NaN"
  PUB_DATE: 
    tag: "260"
    code: "c"
    cleaning:
      - func: pattern_extract
        pattern: '(\d{4})'
        group: 1
  NOTE: 
    tag: "500"
    code: "a"
  ALT_ID: 
    tag: "035"
    code: "a"