# config.yaml

source_type: file
source: data/sample.xml

outputs:
  - type: rdf
    format: ttl
  - type: rdf 
    format: jsonld

prefixes:
  dcterms: "http://purl.org/dc/terms/"
  fabio: "http://purl.org/spar/fabio/"
  foaf: "http://xmlns.com/foaf/0.1/"
  rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  schema: "http://schema.org/"
  xsd: "http://www.w3.org/2001/XMLSchema#"

uri_patterns:
  subject_uri: "https://example.org/record/{ID}"
  object_uri: "{subject_uri}/{field}/{index}"

fields:
  ID: 
    tag: "001"
    code: ""
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:identifier"
          object: "{value}"
          datatype: "rdfs:Literal"
  AUTHOR:
    tag: "100"
    code: "a"
    cleaning:
      - func: pattern_replace
        patterns:
          - '[.,!\[\]?:;]+$'
          - '^\s+|\s+$'
        replacement: ""
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:creator"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "rdf:type"
          object: "foaf:Person"
        - subject: "{object_uri}"
          predicate: "foaf:name"
          object: "{value}"
          datatype: "rdfs:Literal"
  TITLE:
    tag: "245"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:title"
          object: "{value}"
          datatype: "rdfs:Literal"
  SUBTITLE:
    tag: "245"
    code: "b"
    cleaning:
      - func: pattern_replace
        patterns:
          - '\s{2,}'
        replacement: " "
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "fabio:hasSubtitle"
          object: "{value}"
          datatype: "rdfs:Literal"
  PUB_PLACE: 
    tag: "260"
    code: "a"
    cleaning:
      - func: pattern_replace
        patterns:
          - '^\s+|\s+$'
        replacement: ""
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "fabio:hasPlaceOfPublication"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "rdf:type"
          object: "schema:Place"
        - subject: "{object_uri}"
          predicate: "schema:name"
          object: "{value}"
          datatype: "rdfs:Literal"
  PUBLISHER: 
    tag: "260"
    code: "b"
    cleaning:
      - func: pattern_replace
        patterns:
          - '\[s\.n\.\]'
          - '\[s\.l\.\]'
          - 'n\.d\.'
          - 'nan'
          - '-'
          - 'none'
        replacement: "NaN"
    mapping:
      type: pattern
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:publisher"
          object: "{object_uri}"
        - subject: "{object_uri}"
          predicate: "rdf:type"
          object: "foaf:Agent"
        - subject: "{object_uri}"
          predicate: "foaf:name"
          object: "{value}"
          datatype: "rdfs:Literal"
  PUB_DATE: 
    tag: "260"
    code: "c"
    cleaning:
      - func: pattern_extract
        pattern: '(\d{4})'
        group: 1
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "fabio:hasPublicationYear"
          object: "{value}"
          datatype: "xsd:gYear"
  NOTE: 
    tag: "500"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:description"
          object: "{value}"
          datatype: "rdfs:Literal"
  ALT_ID: 
    tag: "035"
    code: "a"
    mapping:
      type: direct
      template:
        - subject: "{subject_uri}"
          predicate: "dcterms:identifier"
          object: "{value}"
          datatype: "rdfs:Literal"